/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as CreateMatchRouteImport } from './routes/create-match'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AddStatsRouteImport } from './routes/add-stats'
import { Route as AddPlayerRouteImport } from './routes/add-player'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMatchRoute = CreateMatchRouteImport.update({
  id: '/create-match',
  path: '/create-match',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AddStatsRoute = AddStatsRouteImport.update({
  id: '/add-stats',
  path: '/add-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlayerRoute = AddPlayerRouteImport.update({
  id: '/add-player',
  path: '/add-player',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/add-player': typeof AddPlayerRoute
  '/add-stats': typeof AddStatsRoute
  '/analytics': typeof AnalyticsRoute
  '/create-match': typeof CreateMatchRoute
  '/matches': typeof MatchesRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/scout': typeof ScoutRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/add-player': typeof AddPlayerRoute
  '/add-stats': typeof AddStatsRoute
  '/analytics': typeof AnalyticsRoute
  '/create-match': typeof CreateMatchRoute
  '/matches': typeof MatchesRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/scout': typeof ScoutRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/add-player': typeof AddPlayerRoute
  '/add-stats': typeof AddStatsRoute
  '/analytics': typeof AnalyticsRoute
  '/create-match': typeof CreateMatchRoute
  '/matches': typeof MatchesRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/scout': typeof ScoutRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/add-player'
    | '/add-stats'
    | '/analytics'
    | '/create-match'
    | '/matches'
    | '/players'
    | '/profile'
    | '/reports'
    | '/scout'
    | '/settings'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/add-player'
    | '/add-stats'
    | '/analytics'
    | '/create-match'
    | '/matches'
    | '/players'
    | '/profile'
    | '/reports'
    | '/scout'
    | '/settings'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/add-player'
    | '/add-stats'
    | '/analytics'
    | '/create-match'
    | '/matches'
    | '/players'
    | '/profile'
    | '/reports'
    | '/scout'
    | '/settings'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AddPlayerRoute: typeof AddPlayerRoute
  AddStatsRoute: typeof AddStatsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CreateMatchRoute: typeof CreateMatchRoute
  MatchesRoute: typeof MatchesRoute
  PlayersRoute: typeof PlayersRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ScoutRoute: typeof ScoutRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-match': {
      id: '/create-match'
      path: '/create-match'
      fullPath: '/create-match'
      preLoaderRoute: typeof CreateMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-stats': {
      id: '/add-stats'
      path: '/add-stats'
      fullPath: '/add-stats'
      preLoaderRoute: typeof AddStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-player': {
      id: '/add-player'
      path: '/add-player'
      fullPath: '/add-player'
      preLoaderRoute: typeof AddPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AddPlayerRoute: AddPlayerRoute,
  AddStatsRoute: AddStatsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CreateMatchRoute: CreateMatchRoute,
  MatchesRoute: MatchesRoute,
  PlayersRoute: PlayersRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ScoutRoute: ScoutRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
